# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[(b'1', b'General'), (b'2', b'Management'), (b'3', b'Compensation'), (b'4', b'Suggestions'), (b'5', b'Complaint')], default=b'1', max_length=10),
        ),
    ]
