# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0002_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=500)),
                ('is_read', models.BooleanField()),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
