# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import myems.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('myems', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='departments', through='myems.DeptEmp', to='myems.Departments'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, upload_to=myems.models.upload_path_handler),
        ),
    ]
